# Generated by Django 3.0.6 on 2020-05-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200524_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='areacode',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='may_contact',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='phone_number',
        ),
    ]
