# Generated by Django 3.0.6 on 2020-06-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200602_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='post_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='autheur',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='contenu',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_creation',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contenu',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_creation',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_modification',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titre',
            new_name='title',
        ),
    ]
